### ISSUE TITLE
'info.json' file is missing,how to fix it?

### ISSUE THREAD

**Issue by Mayuemei** [Signaltonsalat/AsFault#54]
First， I use the command of ’asfault evolve mock --generations 2 ‘, which generates map of the road.
Then execute the 'asfault replay run-test C:\Users\2020\.asfaultenv\output\tests\00000026.json' command, the BeamNG console prompts that the info.json file is missing, I try to copy the 'asfault.json' file according to the prompt information put it under 'levels/asfault/' and rename it to 'info.json', where {{prefab}} is already the correct paththe，but result shows 'info.json' parse error.
So I want to know why the 'info.json' file is missing and how to fix it?
Thank you all for your help!

**Comment by neelofarhassan** [comment]
Hi,
I am getting the same error message. When I copied asfault.json as info.json, the parsing error resulted. Any idea how to fix this issue?

I am using python3.7 and BeamNG.tech.v0.24

001.680|I|GELua.asfault|Starting up AsFault Lua API
002.677|I|GELua.print|*************LightRayPostFX 2 set
002.687|I|GELua.print|********PostFXSSAOGeneralEnabled 2 set
003.094|E|GELua.core_levels.|No entry point for level found: /levels/asfault. Ignoring level.
003.096|W|GELua.core_levels.|info.json missing: /levels/GridMap/info.json
003.096|E|GELua.core_levels.|No entry point for level found: /levels/GridMap. Ignoring level.
003.812|I|GELua.levelLoading|*** loading level: levels/asfault/info.json
003.812|I|GELua.levelLoading|*** Loading init took: 0.166 s
003.956|I|GELua.levelLoading|*** Loaded datablocks in 0.144 s
003.958|I|GELua.levelLoading|*** Loaded materials in 0.002 s
003.959|E|TS|levels/asfault/info.json Line: 1 - parse error
003.960|E|TS|>>> Advanced script error report.  Line 1.
003.960|E|TS|>>> Some error context, with ## on sides of error halt:
003.961|E|TS|
## ##   {
        "name": "AsFault",
        "description": "AsFault's procedurally generated driving task",
        "authors": "",
        "difficulty": "0",
        "vehicles": {
            "egovehicle": {
                "playerUsable": true,
                "startFocus": true
003.961|E|TS|>>> Error report complete.

**Comment by neelofarhassan** [comment]
Hi,
I am getting the same error message. When I copied asfault.json as info.jason, the parsing error resulted. Any idea how to fix this issue?

I am using python3.7 and [BeamNG.tech.v0.24

001.680|I|GELua.asfault|Starting up AsFault Lua API
002.677|I|GELua.print|*************LightRayPostFX 2 set
002.687|I|GELua.print|********PostFXSSAOGeneralEnabled 2 set
003.094|E|GELua.core_levels.|No entry point for level found: /levels/asfault. Ignoring level.
003.096|W|GELua.core_levels.|info.json missing: /levels/GridMap/info.json
003.096|E|GELua.core_levels.|No entry point for level found: /levels/GridMap. Ignoring level.
003.812|I|GELua.levelLoading|*** loading level: levels/asfault/info.json
003.812|I|GELua.levelLoading|*** Loading init took: 0.166 s
003.956|I|GELua.levelLoading|*** Loaded datablocks in 0.144 s
003.958|I|GELua.levelLoading|*** Loaded materials in 0.002 s
003.959|E|TS|levels/asfault/info.json Line: 1 - parse error
003.960|E|TS|>>> Advanced script error report.  Line 1.
003.960|E|TS|>>> Some error context, with ## on sides of error halt:
003.961|E|TS|
## ##   {
        "name": "AsFault",
        "description": "AsFault's procedurally generated driving task",
        "authors": "",
        "difficulty": "0",
        "vehicles": {
            "egovehicle": {
                "playerUsable": true,
                "startFocus": true
003.961|E|TS|>>> Error report complete.
